import 'package:ezycourse_community/core/shared/models/pagination_meta_model.dart';
import 'package:ezycourse_community/features/community/data/models/community_list_model.dart';

import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'community_list_response_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'community_list_response_model.g.dart';

@freezed
abstract class CommunityListResponseModel with _$CommunityListResponseModel {
  const factory CommunityListResponseModel({
    @JsonKey(name: 'meta') required MetaModel meta,
    @JsonKey(name: 'data') required List<CommunityListModel> data,
  }) = _CommunityListResponseModel;

  factory CommunityListResponseModel.fromJson(Map<String, Object?> json) =>
      _$CommunityListResponseModelFromJson(json);
}
