import 'package:ezycourse_community/features/community/domain/entities/community_channel_entity.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'community_channel_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'community_channel_model.g.dart';

@freezed
abstract class CommunityChannelModel with _$CommunityChannelModel {
  const CommunityChannelModel._();
  const factory CommunityChannelModel({
    @JsonKey(name: "id") required int channelId,

  }) = _CommunityChannelModel;
  

  factory CommunityChannelModel.fromJson(Map<String, Object?> json) => _$CommunityChannelModelFromJson(json);

  CommunityChannelEntity toEntity() {
    return CommunityChannelEntity(
      channelId: channelId,
    );
  }
}

