import 'package:ezycourse_community/features/community/domain/entities/community_list_entity.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'community_list_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'community_list_model.g.dart';

@freezed
abstract class CommunityListModel with _$CommunityListModel {

  const CommunityListModel._();
  
  const factory CommunityListModel({
    @JsonKey(name: 'id') required int id,
    @JsonKey(name: 'title') required String title,
    @JsonKey(name: 'cover') required String coverImage,
    @JsonKey(name: 'total_feeds') required int totalFeeds,
    @JsonKey(name: 'total_members') required int totalMembers,
    @JsonKey(name: 'status') required String status,
    @JsonKey(name: 'thumbnail') required String thumbnail,
  }) = _CommunityListModel;

  factory CommunityListModel.fromJson(Map<String, Object?> json) => _$CommunityListModelFromJson(json);

  CommunityListEntity toEntity() {
    return CommunityListEntity(
      id: id,
      title: title,
      coverImage: coverImage,
      totalFeeds: totalFeeds,
      totalMembers: totalMembers,
      status: status,
      thumbnail: thumbnail,
    );
  }
}