import 'package:ezycourse_community/features/community/domain/entities/comment_user_entity.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'comment_user_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'comment_user_model.g.dart';

@freezed
abstract class CommentUserModel with _$CommentUserModel {
  const CommentUserModel._();
  const factory CommentUserModel({
    required int id,
    @JsonKey(name: "full_name") required String fullName,
    @JsonKey(name: "profile_pic") required String profilePic,
  }) = _CommentUserModel;

  factory CommentUserModel.fromJson(Map<String, Object?> json) => _$CommentUserModelFromJson(json);

  CommentUserEntity toEntity() {
    return CommentUserEntity(
      id: id,
      fullName: fullName,
      profilePic: profilePic,
    );
  }
}