import 'package:ezycourse_community/core/shared/models/pagination_meta_model.dart';
import 'package:ezycourse_community/features/community/data/models/community_list_model.dart';

import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'community_response_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'community_response_model.g.dart';

@freezed
abstract class CommunityResponseModel with _$CommunityResponseModel {
  const factory CommunityResponseModel({
    @JsonKey(name: 'meta') required MetaModel meta,
    @JsonKey(name: 'data') required List<CommunityListModel> data,
  }) = _CommunityResponseModel;

  factory CommunityResponseModel.fromJson(Map<String, Object?> json) =>
      _$CommunityResponseModelFromJson(json);
}
