import 'package:ezycourse_community/features/community/domain/entities/feed_like_entity.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'feed_like_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'feed_like_model.g.dart';

@freezed
abstract class FeedLikeModel with _$FeedLikeModel {
  const FeedLikeModel._();
  
  const factory FeedLikeModel({
    @JsonKey(name: "reaction_type") String? reactionType,
  }) = _FeedLikeModel;

  factory FeedLikeModel.fromJson(Map<String, Object?> json) => _$FeedLikeModelFromJson(json);

  FeedLikeEntity toEntity() {
    return FeedLikeEntity(
      reactionType: reactionType,
    );
  }
}
