import 'package:ezycourse_community/features/community/domain/entities/feed_file_entity.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'feed_file_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'feed_file_model.g.dart';

@freezed
abstract class FeedFileModel with _$FeedFileModel {

  const FeedFileModel._();
  
  const factory FeedFileModel({
    @JsonKey(name: 'fileLoc') required String fileLoc,
    @JsonKey(name: 'originalName') required String fileName,
    @JsonKey(name: 'extname') required String fileExt,
    @JsonKey(name: 'type') required String fileType,
  }) = _FeedFileModel;

  factory FeedFileModel.fromJson(Map<String, Object?> json) => _$FeedFileModelFromJson(json);

  FeedFileEntity toEntity() {
    return FeedFileEntity(
      fileLoc: fileLoc,
      fileName: fileName,
      fileExt: fileExt,
      fileType: fileType,
    );
  }
}