import 'package:ezycourse_community/features/community/data/models/comment_user_model.dart';
import 'package:ezycourse_community/features/community/domain/entities/feed_comment_entity.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'feed_comment_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'feed_comment_model.g.dart';

@freezed
abstract class FeedCommentModel with _$FeedCommentModel {
  const FeedCommentModel._();
  const factory FeedCommentModel({
    required int id,
    @JsonKey(name: "comment_txt") required String commentText,
    required CommentUserModel user,
  }) = _FeedCommentModel;


  factory FeedCommentModel.fromJson(Map<String, Object?> json) => _$FeedCommentModelFromJson(json);

  FeedCommentEntity toEntity() {
    return FeedCommentEntity(
      id: id,
      commentText: commentText,
      user: user.toEntity(),
    );
  }
}

