import 'package:ezycourse_community/features/community/data/models/feed_file_model.dart';
import 'package:ezycourse_community/features/community/data/models/feed_like_model.dart';
import 'package:ezycourse_community/features/community/domain/entities/feed_entity.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'feed_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'feed_model.g.dart';

@freezed
abstract class FeedModel with _$FeedModel {
  // add private constructor
  const FeedModel._();

  const factory FeedModel({
    @JsonKey(name: 'id') required final int id,
    @JsonKey(name: 'school_id') required final int schoolId,
    @JsonKey(name: 'community_id') required final int communityId,
    @JsonKey(name: 'space_id') required final int spaceId,
    @JsonKey(name: 'feed_txt') required final String feedText,
    @JsonKey(name: 'name') required final String userName,
    @JsonKey(name: 'pic') required final String userPic,
    @JsonKey(name: 'created_at') required final DateTime createdAt,


    //ENGAGEMENT FIELDS
    @JsonKey(name:'like_count') required final int likeCount,
    @JsonKey(name:'comment_count') required final int commentCount,
    @JsonKey(name:'share_count') required final int shareCount,

    //User's like/reaction
    @JsonKey(name:'like') final FeedLikeModel? like,

    //Files 
    @JsonKey(name:'files') required final List<FeedFileModel> files,
  }) = _FeedModel;


  factory FeedModel.fromJson(Map<String, Object?> json) =>
      _$FeedModelFromJson(json);

  /// Convert to domain entity
  FeedEntity toEntity() {
    return FeedEntity(
      id: id,
      schoolId: schoolId,
      communityId: communityId,
      spaceId: spaceId,
      feedText: feedText,
      userName: userName,
      userPic: userPic,
      createdAt: createdAt,
      likeCount: likeCount,
      commentCount: commentCount,
      shareCount: shareCount,
      like: like?.toEntity(),
      files: files.map((fileModel) => fileModel.toEntity()).toList(),

    );
  }
}
