import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'community_channel_entity.freezed.dart';


@freezed
abstract class CommunityChannelEntity with _$CommunityChannelEntity {
  const factory CommunityChannelEntity({
    required int channelId,

  }) = _CommunityChannelEntity;


}