import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'community_list_entity.freezed.dart';

@freezed
abstract class CommunityListEntity with _$CommunityListEntity {
  const factory CommunityListEntity({
    required int id,
    required String title,
    required String coverImage,
    required int totalFeeds,
    required int totalMembers,
    required String status,
  }) = _CommunityListEntity;
}
