import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'comment_user_entity.freezed.dart';

@freezed
abstract class CommentUserEntity with _$CommentUserEntity {
  const factory CommentUserEntity({
    required int id,
    required String fullName,
    required String profilePic,
  }) = _CommentUserEntity;
}