import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'feed_like_entity.freezed.dart';

@freezed
abstract class FeedLikeEntity with _$FeedLikeEntity {
  const factory FeedLikeEntity({
    required String? reactionType,
  }) = _FeedLikeEntity;
}
