import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'feed_file_entity.freezed.dart';

@freezed
abstract class FeedFileEntity with _$FeedFileEntity {
  const factory FeedFileEntity({
    required String fileLoc,
    required String fileName,
    required String fileExt,
    required String fileType,
  }) = _FeedFileEntity;
}
