import 'package:ezycourse_community/features/community/domain/entities/comment_user_entity.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'feed_comment_entity.freezed.dart';

@freezed
abstract class FeedCommentEntity with _$FeedCommentEntity {
  const factory FeedCommentEntity({
    required int id,
    required String commentText,
    required CommentUserEntity user,
  }) = _FeedCommentEntity;
}
