import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'feed_entity.freezed.dart';


@freezed
abstract class FeedEntity with _$FeedEntity {
  const factory FeedEntity({
    required int id,
    required int schoolId,
    required int communityId,
    required int spaceId,
    required String feedText,
    required String userName,
    required String userPic,
    required DateTime createdAt,
  }) = _FeedEntity;


}